export const EVIDENCE_SUBMIT_MAX_PHOTOS = 5;
export const EVIDENCE_SUBMIT_MIN_DESCRIPTION = 20;
export const EVIDENCE_SUBMIT_MAX_UPLOAD_DIMENSION = 1280;
export const EVIDENCE_SUBMIT_JPEG_QUALITY = 0.72;
