export const detailCardsStyles = () => {
  return {
    detailScreen: {
      flex: 1,
      backgroundColor: '#FFF6EC',
    },
    detailContent: {
      paddingHorizontal: 16,
      paddingTop: 14,
      paddingBottom: 20,
      gap: 14,
    },
    detailActionDock: {
      marginTop: -34,
      paddingHorizontal: 16,
      gap: 10,
      zIndex: 4,
    },
    detailLeadStack: {
      marginTop: 12,
      paddingHorizontal: 16,
      gap: 12,
      zIndex: 2,
    },
    detailCard: {
      backgroundColor: '#FFFFFF',
      borderRadius: 26,
      padding: 16,
      borderWidth: 1,
      borderColor: '#F0D8BF',
      shadowColor: '#7A3F12',
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.06,
      shadowRadius: 16,
      elevation: 2,
    },
    detailMainCard: {
      backgroundColor: '#FFFFFF',
      borderRadius: 30,
      padding: 18,
      borderWidth: 1,
      borderColor: '#F0D8BF',
      shadowColor: '#7A3F12',
      shadowOffset: { width: 0, height: 10 },
      shadowOpacity: 0.08,
      shadowRadius: 18,
      elevation: 4,
      gap: 14,
    },
    detailMainKickerRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    detailMainPawBadge: {
      width: 32,
      height: 32,
      borderRadius: 12,
      backgroundColor: '#FFF6EC',
      borderWidth: 1,
      borderColor: '#F0D8BF',
      alignItems: 'center',
      justifyContent: 'center',
    },
    detailMainKicker: {
      color: '#A84F16',
      fontSize: 11,
      fontWeight: '900',
      letterSpacing: 0.6,
      textTransform: 'uppercase',
    },
    detailMainTitle: {
      fontSize: 24,
      fontWeight: '900',
      color: '#272A3A',
      lineHeight: 30,
    },
    detailMainMetaRow: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: 8,
      padding: 12,
      borderRadius: 18,
      backgroundColor: '#FFF6EC',
      borderWidth: 1,
      borderColor: '#F0D8BF',
    },
    detailMainMetaText: {
      flex: 1,
      fontSize: 13,
      color: '#8D7D78',
      lineHeight: 18,
      fontWeight: '700',
    },
    detailMainDivider: {
      height: 0.5,
      backgroundColor: '#F0D8BF',
    },
    detailMainSectionLabel: {
      fontSize: 10,
      fontWeight: '800',
      color: '#A84F16',
      letterSpacing: 0.8,
      textTransform: 'uppercase',
      marginBottom: -4,
    },
    detailMainDescription: {
      fontSize: 15,
      color: '#272A3A',
      lineHeight: 23,
    },
    detailMainFooter: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 12,
      paddingTop: 2,
    },
    detailMainRegistrar: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
    },
    detailMainRegistrarCopy: {
      flex: 1,
    },
    detailMainFollowersButton: {
      minHeight: 38,
      paddingHorizontal: 12,
      borderRadius: 999,
      backgroundColor: '#FFF6EC',
      borderWidth: 1,
      borderColor: '#F0D8BF',
      justifyContent: 'center',
    },
    detailMainFollowersText: {
      color: '#A84F16',
      fontSize: 12,
      fontWeight: '900',
    },
    detailSectionHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      marginBottom: 12,
    },
    detailSectionIcon: {
      width: 36,
      height: 36,
      borderRadius: 14,
      backgroundColor: '#FFF6EC',
      borderWidth: 1,
      borderColor: '#F0D8BF',
      alignItems: 'center',
      justifyContent: 'center',
    },
    detailSectionCopy: {
      flex: 1,
    },
    detailSectionLabel: {
      fontSize: 13,
      fontWeight: '900',
      color: '#272A3A',
      letterSpacing: 0.8,
      textTransform: 'uppercase',
    },
    detailSectionHint: {
      marginTop: 2,
      fontSize: 12,
      fontWeight: '700',
      color: '#8D7D78',
    },
    detailMapContainer: {
      height: 154,
      backgroundColor: '#F0D8BF',
      borderRadius: 22,
      overflow: 'hidden',
      marginBottom: 10,
      borderWidth: 1,
      borderColor: '#F0D8BF',
    },
    detailMap: {
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
    },
    detailMapAddress: {
      fontSize: 13,
      color: '#8D7D78',
      lineHeight: 18,
      fontWeight: '700',
    },
    detailMapOpenBadge: {
      position: 'absolute',
      right: 10,
      top: 10,
      width: 34,
      height: 34,
      borderRadius: 13,
      backgroundColor: 'rgba(255,255,255,0.94)',
      borderWidth: 1,
      borderColor: '#F0D8BF',
      alignItems: 'center',
      justifyContent: 'center',
    },
    detailRegistrarName: {
      fontSize: 14,
      fontWeight: '800',
      color: '#272A3A',
    },
    detailRegistrarDate: {
      fontSize: 12,
      color: '#8D7D78',
      marginTop: 2,
    },
  };
};
