import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    marginHorizontal: 16,
    marginTop: 16,
    backgroundColor: "#FFFBEB",
    borderRadius: 12,
    padding: 14,
    borderWidth: 0.5,
    borderColor: "#F59E0B",
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginBottom: 8,
  },
  headerText: {
    fontSize: 14,
    fontWeight: "700",
    color: "#92400E",
  },
  description: {
    fontSize: 13,
    color: "#78716C",
    lineHeight: 18,
    marginBottom: 12,
  },
  requestReason: {
    color: "#57534E",
    fontSize: 13,
    fontWeight: "700",
    marginBottom: 6,
  },
  requestReasonText: {
    color: "#78716C",
    fontSize: 13,
    lineHeight: 18,
    marginBottom: 12,
  },
  actions: {
    flexDirection: "row",
    gap: 10,
  },
  rejectButton: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#E24B4A",
    alignItems: "center",
  },
  rejectText: {
    color: "#E24B4A",
    fontWeight: "700",
    fontSize: 13,
  },
  approveButton: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 10,
    backgroundColor: "#10B981",
    alignItems: "center",
  },
  approveText: {
    color: "#fff",
    fontWeight: "700",
    fontSize: 13,
  },
  loadVoteButton: {
    paddingVertical: 10,
    alignItems: "center",
  },
  loadVoteText: {
    color: "#F59E0B",
    fontWeight: "600",
    fontSize: 13,
  },
  voteDisabled: {
    fontSize: 12,
    color: "#8D7D78",
    fontStyle: "italic",
  },
  voteProgress: {
    backgroundColor: "#FEF3C7",
    borderRadius: 10,
    padding: 12,
    marginBottom: 12,
    gap: 12,
  },
  voteProgressRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  voteProgressLabel: {
    fontSize: 12,
    fontWeight: "700",
    color: "#92400E",
  },
  voteProgressValue: {
    flexShrink: 1,
    textAlign: "right",
    fontSize: 12,
    fontWeight: "700",
    color: "#57534E",
  },
  voteProgressHint: {
    fontSize: 12,
    color: "#78716C",
    lineHeight: 17,
  },
  progressBackground: {
    height: 8,
    borderRadius: 999,
    backgroundColor: "#FDE68A",
    marginTop: 8,
    overflow: "hidden",
  },
  participationProgressFill: {
    height: "100%",
    borderRadius: 999,
    backgroundColor: "#F59E0B",
  },
  approvalProgressFill: {
    height: "100%",
    borderRadius: 999,
    backgroundColor: "#10B981",
  },
  rejectionProgressFill: {
    height: "100%",
    borderRadius: 999,
    backgroundColor: "#E24B4A",
  },
  votedText: {
    fontSize: 13,
    color: "#555",
    fontWeight: "500",
    marginTop: 2,
  },
  selectAllButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginBottom: 10,
  },
  selectAllText: {
    fontSize: 13,
    fontWeight: "600",
    color: "#78716C",
  },
  evidenceCard: {
    backgroundColor: "#FEF3C7",
    borderRadius: 10,
    padding: 12,
    marginBottom: 12,
    borderWidth: 1.5,
    borderColor: "transparent",
  },
  evidenceCardSelected: {
    borderColor: "#F59E0B",
    backgroundColor: "#FEF9C3",
  },
  evidenceCardHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 6,
  },
  evidenceAuthor: {
    fontSize: 12,
    fontWeight: "600",
    color: "#92400E",
  },
  selectionCount: {
    fontSize: 12,
    fontWeight: "600",
    color: "#92400E",
    marginBottom: 10,
    textAlign: "center",
  },
  evidenceDescription: {
    fontSize: 13,
    color: "#272A3A",
    lineHeight: 18,
    marginBottom: 8,
  },
  evidencePhotos: {
    marginTop: 4,
  },
  evidencePhoto: {
    width: 90,
    height: 90,
    borderRadius: 8,
    marginRight: 8,
  },
  fullscreenBackdrop: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.9)",
    justifyContent: "center",
    alignItems: "center",
  },
  fullscreenClose: {
    position: "absolute",
    top: 56,
    right: 16,
    zIndex: 10,
  },
  fullscreenImage: {
    width: "100%",
    height: "80%",
  },
  resolvedSuccessContainer: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 20,
    backgroundColor: "#ECFDF5",
    borderRadius: 10,
    marginTop: 12,
  },
  resolvedSuccessText: {
    fontSize: 16,
    fontWeight: "700",
    color: "#10B981",
    marginTop: 8,
  },
  closedContainer: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 20,
    backgroundColor: "#F5F5F4",
    borderRadius: 10,
    marginTop: 12,
  },
  closedText: {
    fontSize: 16,
    fontWeight: "700",
    color: "#78716C",
    marginTop: 8,
  },
  rejectedContainer: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 20,
    backgroundColor: "#FEF2F2",
    borderRadius: 10,
    marginTop: 12,
  },
  rejectedText: {
    fontSize: 16,
    fontWeight: "700",
    color: "#E24B4A",
    marginTop: 8,
  },
  rejectionExpiryText: {
    fontSize: 12,
    color: "#78716C",
    textAlign: "center",
    marginTop: 10,
    fontStyle: "italic",
  },
  evidenceSelectionSection: {
    marginTop: 16,
    paddingTop: 16,
    borderTopWidth: 0.5,
    borderTopColor: "#F59E0B",
  },
  evidenceSelectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginBottom: 6,
  },
  evidenceSelectionTitle: {
    fontSize: 13,
    fontWeight: "700",
    color: "#92400E",
  },
  evidenceSelectionDescription: {
    fontSize: 12,
    color: "#78716C",
    lineHeight: 17,
    marginBottom: 12,
  },
});
