export const heroStyles = () => {
  return {
    detailHero: {
      height: 264,
      marginTop: 0,
      marginHorizontal: 0,
      backgroundColor: '#FFE8C8',
      position: 'relative',
      overflow: 'hidden',
      shadowColor: '#7A3F12',
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.1,
      shadowRadius: 18,
      elevation: 4,
    },
    detailHeroContent: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
    },
    detailHeroBlobPrimary: {
      position: 'absolute',
      width: 190,
      height: 190,
      borderRadius: 95,
      backgroundColor: 'rgba(255,255,255,0.48)',
      top: -48,
      right: -38,
    },
    detailHeroBlobSecondary: {
      position: 'absolute',
      width: 132,
      height: 132,
      borderRadius: 66,
      backgroundColor: 'rgba(255,255,255,0.32)',
      left: -28,
      bottom: -30,
    },
    detailHeroPawPrint: {
      position: 'absolute',
      width: 64,
      height: 64,
      borderRadius: 24,
      backgroundColor: 'rgba(255,255,255,0.52)',
      alignItems: 'center',
      justifyContent: 'center',
      right: 46,
      bottom: 44,
      transform: [{ rotate: '-10deg' }],
    },
    detailHeroEmoji: {
      fontSize: 82,
      zIndex: 1,
    },
    detailHeroImage: {
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      width: '100%',
      height: '100%',
    },
    detailHeroFade: {
      position: 'absolute',
      left: 0,
      right: 0,
      bottom: 0,
      height: 104,
      zIndex: 2,
    },
    detailHeroHeader: {
      position: 'absolute',
      top: 54,
      left: 16,
      right: 16,
      flexDirection: 'row',
      justifyContent: 'space-between',
      zIndex: 10,
    },
    detailIconButton: {
      width: 44,
      height: 44,
      backgroundColor: 'rgba(255,255,255,0.94)',
      borderRadius: 16,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1,
      borderColor: '#F0D8BF',
    },
    detailMapModalButton: {
      position: 'absolute',
      top: 20,
      left: 15,
      width: 44,
      height: 44,
      backgroundColor: 'rgba(255,255,255,0.94)',
      borderRadius: 16,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1,
      borderColor: '#F0D8BF',
    },
  };
};
