export const infoBarStyles = () => {
  return {
    detailHeroFooter: {
      padding: 12,
      gap: 12,
      backgroundColor: '#FFFCF7',
      borderRadius: 24,
      borderWidth: 1,
      borderColor: '#F0D8BF',
      shadowColor: '#7A3F12',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.04,
      shadowRadius: 10,
      elevation: 1,
    },
    detailPillRow: {
      flexDirection: 'row',
      gap: 8,
      flexWrap: 'wrap',
    },
    detailPill: {
      paddingVertical: 6,
      paddingHorizontal: 12,
      borderRadius: 999,
      borderWidth: 1,
      borderColor: '#F0D8BF',
      backgroundColor: '#FFFFFF',
    },
    detailPillText: {
      fontSize: 11,
      fontWeight: '800',
      color: '#712B13',
    },
    detailMetaGrid: {
      flexDirection: 'row',
      gap: 10,
    },
    detailMetaItem: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      minHeight: 56,
      padding: 10,
      borderRadius: 18,
      backgroundColor: '#FFFFFF',
      borderWidth: 1,
      borderColor: '#F0D8BF',
    },
    detailMetaIconBox: {
      width: 34,
      height: 34,
      borderRadius: 13,
      backgroundColor: '#FFF6EC',
      alignItems: 'center',
      justifyContent: 'center',
    },
    detailMetaCopy: {
      flex: 1,
      minWidth: 0,
    },
    detailMetaLabel: {
      color: '#A84F16',
      fontSize: 10,
      fontWeight: '900',
      textTransform: 'uppercase',
      letterSpacing: 0.4,
      marginBottom: 2,
    },
    detailMetaText: {
      fontSize: 12,
      color: '#272A3A',
      fontWeight: '800',
    },
    detailMetaIcon: {
      fontSize: 17,
    },
    statusUpdateContainer: {
      gap: 8,
    },
    statusUpdateButton: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
      backgroundColor: '#FF8C42',
      paddingVertical: 12,
      paddingHorizontal: 20,
      borderRadius: 18,
      minHeight: 52,
      borderWidth: 1,
      borderColor: '#FFFFFF',
    },
    statusUpdateButtonText: {
      color: '#fff',
      fontSize: 14,
      fontWeight: '600',
    },
    volunteerButton: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
      backgroundColor: '#10B981',
      paddingVertical: 12,
      paddingHorizontal: 20,
      borderRadius: 18,
      minHeight: 52,
      borderWidth: 1,
      borderColor: '#FFFFFF',
      shadowColor: '#7A3F12',
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.1,
      shadowRadius: 14,
      elevation: 3,
    },
    evidenceButton: {
      backgroundColor: '#FF8C42',
    },
    volunteerButtonActive: {
      backgroundColor: '#DDF7EC',
      borderWidth: 1,
      borderColor: '#10B981',
    },
    volunteerButtonText: {
      color: '#fff',
      fontSize: 14,
      fontWeight: '600',
    },
    volunteerButtonActiveText: {
      color: '#10B981',
    },
    statusModalBackdrop: {
      flex: 1,
      backgroundColor: 'rgba(0,0,0,0.45)',
      justifyContent: 'flex-end',
    },
    statusModalCard: {
      backgroundColor: '#FFFFFF',
      borderTopLeftRadius: 24,
      borderTopRightRadius: 24,
      padding: 18,
      paddingBottom: 28,
    },
    statusModalTitle: {
      color: '#272A3A',
      fontSize: 18,
      fontWeight: '800',
    },
    statusModalText: {
      color: '#8D7D78',
      fontSize: 14,
      lineHeight: 20,
      marginTop: 8,
    },
    statusModalTransition: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 12,
      marginTop: 16,
      marginBottom: 8,
      paddingVertical: 12,
      backgroundColor: '#FFF6EC',
      borderRadius: 16,
    },
    statusModalArrow: {
      fontSize: 18,
      color: '#8D7D78',
      fontWeight: '600',
    },
    statusModalActions: {
      flexDirection: 'row',
      gap: 10,
      marginTop: 18,
    },
    statusModalCancelButton: {
      flex: 1,
      minHeight: 46,
      borderRadius: 16,
      borderWidth: 0.5,
      borderColor: '#F0D8BF',
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: '#FFF6EC',
    },
    statusModalCancelText: {
      color: '#272A3A',
      fontSize: 14,
      fontWeight: '700',
    },
    statusModalConfirmButton: {
      flex: 1,
      minHeight: 46,
      borderRadius: 16,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: '#FF9F1C',
    },
    statusModalConfirmText: {
      color: '#fff',
      fontSize: 14,
      fontWeight: '700',
    },
  };
};
