import { StyleSheet } from 'react-native';

export const requestValidationStyles = StyleSheet.create({
  container: {
    marginHorizontal: 16,
    marginTop: 14,
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    padding: 16,
    borderWidth: 1,
    borderColor: '#F0D8BF',
    shadowColor: '#7A3F12',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.05,
    shadowRadius: 14,
    elevation: 2,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 8,
  },
  title: {
    color: '#272A3A',
    fontSize: 15,
    fontWeight: '900',
  },
  description: {
    color: '#8D7D78',
    fontSize: 13,
    lineHeight: 18,
    marginBottom: 12,
  },
  button: {
    alignItems: 'center',
    backgroundColor: '#FF8C42',
    borderRadius: 18,
    minHeight: 48,
    justifyContent: 'center',
    paddingVertical: 12,
  },
  buttonText: {
    color: '#fff',
    fontSize: 13,
    fontWeight: '800',
  },
  backdrop: {
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.45)',
    flex: 1,
    justifyContent: 'center',
    padding: 20,
  },
  card: {
    backgroundColor: '#fff',
    borderRadius: 24,
    padding: 18,
    width: '100%',
  },
  modalTitle: {
    color: '#272A3A',
    fontSize: 18,
    fontWeight: '800',
    marginBottom: 6,
  },
  modalDescription: {
    color: '#78716C',
    fontSize: 13,
    lineHeight: 18,
    marginBottom: 14,
  },
  reasonOption: {
    alignItems: 'center',
    borderColor: '#F0D8BF',
    borderRadius: 16,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 8,
    marginBottom: 8,
    padding: 12,
  },
  reasonOptionSelected: {
    backgroundColor: '#FFF6EC',
    borderColor: '#FF8C42',
  },
  reasonOptionText: {
    color: '#44403C',
    flex: 1,
    fontSize: 13,
    fontWeight: '600',
  },
  reasonOptionDisabled: {
    opacity: 0.5,
  },
  reasonOptionTextDisabled: {
    color: '#A8A29E',
  },
  reasonOptionHint: {
    fontSize: 11,
    color: '#A8A29E',
    fontStyle: 'italic',
  },
  input: {
    backgroundColor: '#FFF6EC',
    borderColor: '#F0D8BF',
    borderRadius: 16,
    borderWidth: 1,
    color: '#292524',
    fontSize: 13,
    minHeight: 92,
    padding: 12,
    textAlignVertical: 'top',
  },
  actions: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 14,
  },
  cancelButton: {
    alignItems: 'center',
    borderColor: '#F0D8BF',
    borderRadius: 16,
    borderWidth: 1,
    flex: 1,
    paddingVertical: 12,
  },
  cancelText: {
    color: '#57534E',
    fontSize: 13,
    fontWeight: '700',
  },
  confirmButton: {
    alignItems: 'center',
    backgroundColor: '#FF8C42',
    borderRadius: 16,
    flex: 1,
    paddingVertical: 12,
  },
  confirmText: {
    color: '#fff',
    fontSize: 13,
    fontWeight: '800',
  },
  disabledButton: {
    opacity: 0.7,
  },
  evidenceScrollView: {
    maxHeight: 300,
    marginBottom: 10,
  },
  evidenceCard: {
    backgroundColor: '#FFF6EC',
    borderRadius: 18,
    padding: 12,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: '#F0D8BF',
  },
  evidenceCardSelected: {
    borderColor: '#FF8C42',
    backgroundColor: '#FFE8C8',
  },
  evidenceCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 6,
  },
  evidenceAuthor: {
    fontSize: 12,
    fontWeight: '800',
    color: '#A84F16',
  },
  evidenceCardDescription: {
    fontSize: 13,
    color: '#272A3A',
    lineHeight: 18,
    marginBottom: 6,
  },
  evidencePhotos: {
    marginTop: 4,
  },
  evidencePhoto: {
    width: 74,
    height: 74,
    borderRadius: 14,
    marginRight: 6,
  },
  evidenceSelectionCount: {
    fontSize: 12,
    fontWeight: '600',
    color: '#92400E',
    textAlign: 'center',
    marginBottom: 8,
  },
});
