import { StyleSheet } from 'react-native';

export const onboardingStyles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: '#FFF6EC',
    overflow: 'hidden',
  },
  backgroundImage: {
    ...StyleSheet.absoluteFillObject,
    width: '100%',
    height: '100%',
  },
  heroWrap: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'flex-end',
    paddingHorizontal: 18,
    paddingBottom: 0,
    zIndex: 3,
  },
  heroImage: {
    width: '120%',
    maxWidth: 460,
    marginBottom: -34,
  },
  contentSheet: {
    marginTop: -48,
    paddingHorizontal: 30,
    paddingTop: 70,
    paddingBottom: 14,
    alignItems: 'center',
    borderTopLeftRadius: 42,
    borderTopRightRadius: 42,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: 'rgba(240,216,191,0.72)',
    borderTopColor: 'rgba(240,216,191,0.42)',
    shadowColor: '#C9843A',
    shadowOffset: { width: 0, height: -14 },
    shadowOpacity: 0.12,
    shadowRadius: 26,
    elevation: 8,
  },
  sheetTopGradient: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: -36,
    height: 68,
    borderTopLeftRadius: 42,
    borderTopRightRadius: 42,
  },
  title: {
    maxWidth: 315,
    color: '#272A3A',
    fontSize: 33,
    lineHeight: 38,
    fontWeight: '900',
    textAlign: 'center',
    letterSpacing: 0,
  },
  titleCompact: {
    fontSize: 30,
    lineHeight: 35,
  },
  cardText: {
    maxWidth: 320,
    marginTop: 14,
    color: '#8D7D78',
    fontSize: 16,
    lineHeight: 22,
    fontWeight: '700',
    textAlign: 'center',
  },
  primaryButton: {
    width: '100%',
    minHeight: 64,
    marginTop: 26,
    paddingLeft: 28,
    paddingRight: 8,
    borderRadius: 32,
    backgroundColor: '#FF9F1C',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  primaryButtonText: {
    flex: 1,
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: '900',
    textAlign: 'center',
  },
  buttonIconBadge: {
    width: 54,
    height: 54,
    borderRadius: 27,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFF7EC',
    borderWidth: 1,
    borderColor: 'rgba(255,159,28,0.24)',
  },
});
