import { StyleSheet } from 'react-native';

export const adminModerationStyles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: '#FFF6EC',
  },
  listContent: {
    paddingHorizontal: 16,
    paddingBottom: 30,
  },
  header: {
    paddingTop: 8,
    paddingBottom: 16,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  iconButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#F0D8BF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerText: {
    flex: 1,
    minWidth: 0,
  },
  kicker: {
    color: '#8D7D78',
    fontSize: 11,
    fontWeight: '900',
    letterSpacing: 0,
    textTransform: 'uppercase',
  },
  heading: {
    color: '#272A3A',
    fontSize: 28,
    fontWeight: '900',
  },
  subtitle: {
    color: '#8D7D78',
    fontSize: 14,
    fontWeight: '700',
    marginTop: 2,
  },
  card: {
    marginBottom: 12,
    padding: 12,
    borderRadius: 8,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#F0D8BF',
  },
  photoFrame: {
    width: '100%',
    aspectRatio: 16 / 9,
    borderRadius: 8,
    backgroundColor: '#FFE8C8',
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
    marginBottom: 12,
  },
  photo: {
    width: '100%',
    height: '100%',
  },
  cardTitle: {
    color: '#272A3A',
    fontSize: 18,
    lineHeight: 23,
    fontWeight: '900',
  },
  cardDescription: {
    color: '#5F5660',
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '600',
    marginTop: 6,
  },
  metaRow: {
    minHeight: 22,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginTop: 8,
  },
  metaText: {
    flex: 1,
    color: '#8D7D78',
    fontSize: 13,
    lineHeight: 18,
    fontWeight: '700',
  },
  actionsRow: {
    marginTop: 14,
    flexDirection: 'row',
    gap: 8,
  },
  actionButton: {
    flex: 1,
    minHeight: 44,
    borderRadius: 8,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 6,
  },
  actionText: {
    fontSize: 12,
    fontWeight: '900',
  },
  emptyState: {
    minHeight: 220,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 24,
  },
  emptyTitle: {
    color: '#272A3A',
    fontSize: 18,
    fontWeight: '900',
    marginTop: 10,
  },
  emptyText: {
    color: '#8D7D78',
    fontSize: 14,
    textAlign: 'center',
    marginTop: 6,
  },
  modalBackdrop: {
    flex: 1,
    padding: 18,
    backgroundColor: 'rgba(39,42,58,0.42)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalCard: {
    width: '100%',
    maxWidth: 420,
    borderRadius: 8,
    backgroundColor: '#FFFFFF',
    padding: 18,
  },
  modalTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  modalTitle: {
    flex: 1,
    color: '#272A3A',
    fontSize: 18,
    fontWeight: '900',
  },
  modalText: {
    color: '#5F5660',
    fontSize: 14,
    lineHeight: 20,
    marginTop: 10,
  },
  reasonInput: {
    minHeight: 118,
    marginTop: 14,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#F0D8BF',
    backgroundColor: '#FFF6EC',
    color: '#272A3A',
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '600',
  },
  modalActions: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 10,
    marginTop: 16,
  },
  cancelButton: {
    minWidth: 104,
    minHeight: 46,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#F0D8BF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  cancelText: {
    color: '#272A3A',
    fontSize: 14,
    fontWeight: '900',
  },
  confirmButton: {
    minWidth: 104,
    minHeight: 46,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  confirmText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '900',
  },
  disabledButton: {
    opacity: 0.6,
  },
});
