import { StyleSheet } from 'react-native';

export const editProfileStyles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: '#FFF6EC',
  },
  backgroundImage: {
    ...StyleSheet.absoluteFillObject,
  },
  keyboardView: {
    flex: 1,
  },
  content: {
    flexGrow: 1,
    paddingHorizontal: 18,
    paddingTop: 58,
    paddingBottom: 28,
    gap: 18,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  iconButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.9)',
    borderWidth: 1,
    borderColor: 'rgba(240,216,191,0.82)',
  },
  headerText: {
    flex: 1,
    minWidth: 0,
  },
  eyebrow: {
    color: '#8D7D78',
    fontSize: 11,
    fontWeight: '900',
    textTransform: 'uppercase',
    letterSpacing: 0,
  },
  title: {
    color: '#272A3A',
    fontSize: 28,
    fontWeight: '900',
    marginTop: 2,
  },
  card: {
    flex: 1,
    minHeight: 420,
    borderRadius: 34,
    backgroundColor: 'rgba(255,255,255,0.92)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.78)',
    padding: 18,
    alignItems: 'center',
    shadowColor: '#C9843A',
    shadowOffset: { width: 0, height: 16 },
    shadowOpacity: 0.12,
    shadowRadius: 28,
    elevation: 8,
  },
  avatarSection: {
    alignItems: 'center',
    gap: 12,
    marginTop: 8,
  },
  avatarFrame: {
    width: 132,
    height: 132,
    borderRadius: 66,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 6,
    borderColor: '#FFF1DD',
    overflow: 'hidden',
  },
  avatarImage: {
    width: '100%',
    height: '100%',
  },
  changePhotoButton: {
    minHeight: 44,
    paddingHorizontal: 18,
    borderRadius: 22,
    backgroundColor: '#FFE8C8',
    borderWidth: 1,
    borderColor: '#F0D8BF',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  changePhotoText: {
    color: '#A84F16',
    fontSize: 14,
    fontWeight: '900',
  },
  form: {
    width: '100%',
    gap: 10,
    marginTop: 24,
  },
  labelRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  label: {
    color: '#8D7D78',
    fontSize: 12,
    fontWeight: '900',
    textTransform: 'uppercase',
    letterSpacing: 0,
  },
  input: {
    minHeight: 54,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: '#F0D8BF',
    backgroundColor: '#FFFDF9',
    paddingHorizontal: 16,
    color: '#272A3A',
    fontSize: 16,
    fontWeight: '700',
  },
  autocompleteWrap: {
    gap: 8,
  },
  suggestionsList: {
    borderRadius: 18,
    backgroundColor: '#FFFDF9',
    borderWidth: 1,
    borderColor: '#F0D8BF',
    overflow: 'hidden',
  },
  suggestionItem: {
    minHeight: 44,
    paddingHorizontal: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(240,216,191,0.58)',
  },
  suggestionText: {
    flex: 1,
    color: '#272A3A',
    fontSize: 14,
    fontWeight: '800',
  },
  textArea: {
    minHeight: 116,
    paddingTop: 14,
    lineHeight: 22,
  },
  counterText: {
    color: '#8D7D78',
    fontSize: 12,
    fontWeight: '800',
    fontVariant: ['tabular-nums'],
  },
  helpText: {
    color: '#8D7D78',
    fontSize: 13,
    lineHeight: 18,
  },
  footer: {
    width: '100%',
    marginTop: 30,
    gap: 10,
  },
  saveButton: {
    minHeight: 54,
    borderRadius: 27,
    backgroundColor: '#FF9F1C',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  saveButtonDisabled: {
    opacity: 0.58,
  },
  saveButtonText: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '900',
  },
  cancelButton: {
    minHeight: 50,
    borderRadius: 25,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#F0D8BF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  cancelButtonText: {
    color: '#8D7D78',
    fontSize: 14,
    fontWeight: '900',
  },
});
