import { StyleSheet } from 'react-native';

export const profileStyles = (colorScheme) => {
  const isDark = colorScheme === 'dark';
  const background = isDark ? '#FFF6EC' : '#FFF6EC';
  const surface = 'rgba(255,255,255,0.86)';
  const surfaceStrong = 'rgba(255,255,255,0.94)';
  const surfaceSoft = '#FFE8C8';
  const text = '#272A3A';
  const muted = '#8D7D78';
  const border = 'rgba(240,216,191,0.82)';

  return StyleSheet.create({
    screen: {
      flex: 1,
      backgroundColor: background,
    },
    backgroundImage: {
      ...StyleSheet.absoluteFillObject,
    },
    listContent: {
      paddingBottom: 108,
    },
    followedOnlyListContent: {
      paddingTop: 48,
      paddingBottom: 108,
    },
    followedOnlyHeader: {
      marginHorizontal: 18,
      marginBottom: 16,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
    },
    hero: {
      height: 240,
      marginHorizontal: 0,
      marginTop: 0,
    },
    heroActions: {
      position: 'absolute',
      top: 52,
      left: 18,
      right: 18,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      zIndex: 3,
    },
    heroIconButton: {
      width: 44,
      height: 44,
      borderRadius: 22,
      backgroundColor: 'rgba(255,255,255,0.86)',
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1,
      borderColor: 'rgba(240,216,191,0.76)',
      shadowColor: '#C9843A',
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0.1,
      shadowRadius: 12,
      elevation: 3,
    },
    heroIconButtonPlaceholder: {
      width: 40,
      height: 40,
    },
    profileBody: {
      alignItems: 'center',
      marginHorizontal: 18,
      marginTop: -70,
      paddingHorizontal: 20,
      paddingTop: 18,
      paddingBottom: 20,
      borderRadius: 34,
      backgroundColor: surface,
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.78)',
      shadowColor: '#C9843A',
      shadowOffset: { width: 0, height: 16 },
      shadowOpacity: 0.14,
      shadowRadius: 28,
      elevation: 8,
    },
    avatarWrap: {
      width: 124,
      height: 124,
      borderRadius: 62,
      backgroundColor: '#FFFFFF',
      alignItems: 'center',
      justifyContent: 'center',
      marginTop: -56,
      marginBottom: 14,
      borderWidth: 6,
      borderColor: '#FFF1DD',
      shadowColor: '#FF9F1C',
      shadowOffset: { width: 0, height: 10 },
      shadowOpacity: 0.16,
      shadowRadius: 18,
      elevation: 6,
    },
    name: {
      color: text,
      fontSize: 26,
      fontWeight: '900',
      textAlign: 'center',
    },
    username: {
      color: muted,
      fontSize: 14,
      fontWeight: '700',
      marginTop: 5,
      textAlign: 'center',
    },
    bio: {
      color: muted,
      fontSize: 15,
      lineHeight: 22,
      textAlign: 'center',
      marginTop: 14,
      maxWidth: 330,
    },
    profileStatsRow: {
      width: '100%',
      minHeight: 70,
      marginTop: 18,
      paddingHorizontal: 10,
      borderRadius: 24,
      backgroundColor: 'rgba(255,246,236,0.78)',
      borderWidth: 1,
      borderColor: 'rgba(240,216,191,0.76)',
      flexDirection: 'row',
      alignItems: 'center',
    },
    profileStat: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
    },
    profileStatValue: {
      color: '#FF9F1C',
      fontSize: 22,
      fontWeight: '900',
      fontVariant: ['tabular-nums'],
    },
    profileStatLabel: {
      color: muted,
      fontSize: 12,
      fontWeight: '800',
      marginTop: 2,
    },
    profileStatDivider: {
      width: 1,
      height: 38,
      backgroundColor: 'rgba(240,216,191,0.9)',
    },
    badgesRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      justifyContent: 'center',
      gap: 8,
      marginTop: 16,
    },
    profileActionButton: {
      width: '100%',
      minHeight: 54,
      marginTop: 18,
      paddingHorizontal: 18,
      borderRadius: 27,
      backgroundColor: '#FF9F1C',
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
    },
    profileActionButtonText: {
      color: '#FFFFFF',
      fontSize: 15,
      fontWeight: '900',
    },
    accountStatusCard: {
      width: '100%',
      marginTop: 14,
      padding: 14,
      borderRadius: 22,
      backgroundColor: 'rgba(255,246,236,0.72)',
      borderWidth: 1,
      borderColor: 'rgba(240,216,191,0.72)',
      gap: 10,
    },
    accountStatusItem: {
      minHeight: 24,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    accountStatusText: {
      flex: 1,
      color: muted,
      fontSize: 13,
      fontWeight: '800',
    },
    badge: {
      minHeight: 32,
      paddingHorizontal: 14,
      borderRadius: 999,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1,
    },
    badgeText: {
      fontSize: 12,
      fontWeight: '900',
    },
    orangeBadge: {
      backgroundColor: '#FFF1DD',
      borderColor: '#F5C993',
    },
    orangeBadgeText: {
      color: '#A84F16',
    },
    greenBadge: {
      backgroundColor: '#E6F3E8',
      borderColor: '#BFDAC7',
    },
    greenBadgeText: {
      color: '#1A936F',
    },
    blueBadge: {
      backgroundColor: '#F0EAFE',
      borderColor: '#D9CDF7',
    },
    blueBadgeText: {
      color: '#7C5CFF',
    },
    sectionHeader: {
      marginHorizontal: 18,
      marginTop: 18,
      marginBottom: 12,
      paddingHorizontal: 18,
      paddingVertical: 14,
      borderRadius: 24,
      backgroundColor: 'rgba(255,255,255,0.72)',
      borderWidth: 1,
      borderColor: 'rgba(240,216,191,0.7)',
    },
    sectionKicker: {
      color: muted,
      fontSize: 11,
      fontWeight: '900',
      letterSpacing: 0,
      textTransform: 'uppercase',
    },
    sectionTitle: {
      color: text,
      fontSize: 18,
      fontWeight: '900',
      marginTop: 4,
    },
    emptyWrap: {
      marginHorizontal: 18,
      minHeight: 140,
      borderRadius: 26,
      backgroundColor: surface,
      borderWidth: 1,
      borderColor: border,
      alignItems: 'center',
      justifyContent: 'center',
      padding: 18,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0.04,
      shadowRadius: 12,
      elevation: 6,
    },
    emptyTitle: {
      color: text,
      fontSize: 15,
      fontWeight: '800',
    },
    emptyText: {
      color: muted,
      fontSize: 13,
      textAlign: 'center',
      marginTop: 6,
      lineHeight: 18,
    },
    card: {
      marginHorizontal: 18,
      marginBottom: 12,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      minHeight: 88,
      padding: 14,
      borderRadius: 26,
      backgroundColor: surfaceStrong,
      borderWidth: 1,
      borderColor: border,
      shadowColor: '#C9843A',
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.08,
      shadowRadius: 16,
      elevation: 4,
    },
    cardThumb: {
      width: 60,
      height: 60,
      borderRadius: 18,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: surfaceSoft,
      overflow: 'hidden',
      borderWidth: 0.5,
      borderColor: 'rgba(240,216,191,0.8)',
    },
    cardEmoji: {
      fontSize: 28,
    },
    cardBody: {
      flex: 1,
      minWidth: 0,
    },
    cardTitle: {
      color: text,
      fontSize: 15,
      fontWeight: '900',
      lineHeight: 20,
    },
    cardMetaRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      marginTop: 6,
    },
    statusPill: {
      paddingHorizontal: 8,
      paddingVertical: 4,
      borderRadius: 999,
      backgroundColor: '#FFE8C8',
      borderWidth: 0.5,
      borderColor: '#F0D8BF',
    },
    statusText: {
      color: '#FF9F1C',
      fontSize: 11,
      fontWeight: '900',
    },
    cardAddress: {
      flex: 1,
      color: muted,
      fontSize: 12,
    },
    authRequiredScreen: {
      flex: 1,
      backgroundColor: background,
      alignItems: 'center',
      justifyContent: 'center',
    },
    authRequiredCard: {
      width: '88%',
      maxWidth: 340,
      alignItems: 'center',
      padding: 24,
      borderRadius: 34,
      backgroundColor: surface,
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.78)',
      shadowColor: '#C9843A',
      shadowOffset: { width: 0, height: 16 },
      shadowOpacity: 0.14,
      shadowRadius: 28,
      elevation: 8,
    },
    authRequiredTitle: {
      color: text,
      fontSize: 28,
      fontWeight: '900',
      textAlign: 'center',
    },
    authRequiredText: {
      color: muted,
      fontSize: 15,
      lineHeight: 21,
      textAlign: 'center',
      maxWidth: 330,
      marginTop: 8,
      marginBottom: 18,
    },
    authRequiredButton: {
      minHeight: 46,
      paddingHorizontal: 22,
      borderRadius: 999,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: '#FF9F1C',
    },
    authRequiredButtonText: {
      color: '#fff',
      fontSize: 14,
      fontWeight: '900',
    },
    profileMenuBackdrop: {
      flex: 1,
      backgroundColor: 'transparent',
    },
    profileMenuDismissArea: {
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
    },
    profileMenu: {
      position: 'absolute',
      top: 94,
      right: 14,
      width: 164,
      borderRadius: 14,
      backgroundColor: '#FFFFFF',
      borderWidth: 0.5,
      borderColor: '#F0D8BF',
      overflow: 'hidden',
      elevation: 8,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.18,
      shadowRadius: 16,
    },
    profileMenuItem: {
      minHeight: 48,
      paddingHorizontal: 14,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
    },
    profileMenuText: {
      color: '#272A3A',
      fontSize: 14,
      fontWeight: '700',
    },
    profileMenuDangerText: {
      color: '#E24B4A',
      fontSize: 14,
      fontWeight: '700',
    },
    notificationHeader: {
      width: '100%',
      alignItems: 'flex-end',
      paddingTop: 12,
      paddingRight: 16,
    },
    heroRightActions: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    nameRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
    },
  });
};
